---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(p8105.datasets)
```

```{r}
#filter dataset with variables boro, cuisine_description, inspection_date, score, grade only
nyc_restaurant = rest_inspec %>% 
  select(boro, cuisine_description, inspection_date, score, grade) %>% 
  filter(.data = ., boro == "MANHATTAN") %>% 
  na.omit()
```

Column {data-width=650}
-----------------------------------------------------------------------

### Bar Plot with the Grade of NYC Restaurants

```{r}
nyc_restaurant %>% 
  group_by(cuisine_description, grade) %>% 
  summarize(count = n()) %>% 
  plot_ly(
    y = ~count, x = ~cuisine_description, color = ~grade, 
    type = "bar", colors = "viridis"
  )
```

Column {data-width=350}
-----------------------------------------------------------------------

### Box Plot of the Inspection Score of NYC Restaurants

```{r}
nyc_restaurant %>% 
  mutate(cuisine_description = fct_reorder(cuisine_description, score)) %>% 
  plot_ly(y = ~score, color = ~cuisine_description, type = "box", colors = "viridis")
```

### Chart C

```{r}

```

